DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS PRODUCT_DETAIL;
DROP TABLE IF EXISTS SUPPLIER;
 
CREATE TABLE PRODUCT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  product_detail_id INT NOT NULL,
  id_shipping_detail INT NOT NULL,
  id_supplier INT NOT NULL
);

CREATE TABLE PRODUCT_DETAIL (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  brand VARCHAR(250) NOT NULL,
  type VARCHAR(250) NOT NULL,
  location VARCHAR(250) NOT NULL
);

CREATE TABLE SUPPLIER(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  type VARCHAR(250) NOT NULL
);